### PR TITLE
Add qualifiers

### PR DESCRIPTION
**Pull request by gaurav**
This PR is a first stab at adding qualifiers by trying to add anatomical entity qualifiers for one specific set of triples. This will need to be improved as we add more qualifiers, but this basic implementation should be good enough for now.

Also adds `-j` to Souffle runs so it tries to use multiple cores when it can (see #160).

### CODE REVIEW

**Review by balhoff — APPROVED** [review]
This looks good to start off with! Should we go ahead and define a "format" for the qualifier column, assuming we will have multiple qualifiers in future? Something like a JSON object string?

**Comment by gaurav** [comment]
> This looks good to start off with! Should we go ahead and define a "format" for the qualifier column, assuming we will have multiple qualifiers in future? Something like a JSON object string?

This PR doesn't actually produce that final format yet -- it only has a single qualifier-key and qualifier-value on each line, so for e.g. you might see:

```
s p o g [blank] [blank] <-- the unqualified node
s p o g qualifier1 value1
s p o g qualifier2 value2
```

I was thinking of a hacky format where we could aggregate this as:
```
s p o g qualifier1=value1&&qualifier2=value2
```

which should be a bit easier to aggregate than by creating an entire JSON object -- however, assuming that's not too hard to do in Souffle/whatever downstream tool we use, that _would_ be a lot easier to validate and use, and might be easier to Evan to integrate into ORION. Let me shoot him a question on Slack and we can take it from there.

**Comment by balhoff** [comment]
Just to note—we discussed that aggregating qualifiers must be done at the instance level, before mapping subjects and objects to Biolink.

**Comment by gaurav** [comment]
Next steps:
- [x] The proposed aggregation output (`qualifier1=value1&qualifier2=value2`) does make sense in the context of the qualifier list that TRAPI uses (https://github.com/NCATSTranslator/ReasonerAPI/blob/master/docs/reference.md#edge-).
- [ ] We need to modify this PR to work on instance-level data (Gaurav to take a first stab at this early next week)
- [ ] Adding aggregation using the method Jim came up with.

**Comment by gaurav** [comment]
@balhoff I've now modified this PR to fully support aggregation of qualifiers AND compacting of IRIs in qualifiers. The syntax needs to be a little icky in `kg_edges.csv` to limit the probability that a qualifier value could accidentally make it difficult to parse the qualifier list without making the Souffle code overly complicated:

```
<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5660649>	<https://w3id.org/biolink/vocab/affects>	<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5607656>	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(<https://w3id.org/biolink/vocab/anatomical_context_qualifier>=((<http://purl.obolibrary.org/obo/GO_0005654>)))
<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5660649>	<https://w3id.org/biolink/vocab/affects>	<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5660657>	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(<https://w3id.org/biolink/vocab/anatomical_context_qualifier>=((<http://purl.obolibrary.org/obo/GO_0005654>)))
<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5660649>	<https://w3id.org/biolink/vocab/affects>	<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5624468>	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(<https://w3id.org/biolink/vocab/anatomical_context_qualifier>=((<http://purl.obolibrary.org/obo/GO_0005654>)))
<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5660649>	<https://w3id.org/biolink/vocab/affects>	<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5624488>	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(<https://w3id.org/biolink/vocab/anatomical_context_qualifier>=((<http://purl.obolibrary.org/obo/GO_0005654>)))
<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5660649>	<https://w3id.org/biolink/vocab/affects>	<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5660656>	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(<https://w3id.org/biolink/vocab/anatomical_context_qualifier>=((<http://purl.obolibrary.org/obo/GO_0005654>)))
<http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-5660649>	<https://w3id.org/biolink/vocab/affects>	<http://identifiers.org/uniprot/Q01201>	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(<https://w3id.org/biolink/vocab/anatomical_context_qualifier>=((<http://purl.obolibrary.org/obo/GO_0005654>)))
```

But then we can change it into whatever makes sense in compact_iris.sc, including JSON or whatever. I've left it in a simple and hacky format for now, but if you have a cleaner format to suggest (that's easy to implement in Scala!), please let me know:

```
REACTO:R-HSA-390765	biolink:affects	UniProtKB:P06241	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(biolink:anatomical_context_qualifier=GO:0005829)
REACTO:R-HSA-390765	biolink:affects	REACTO:R-HSA-1027362	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(biolink:anatomical_context_qualifier=GO:0005829)
REACTO:R-HSA-390765	biolink:affects	REACTO:R-HSA-1027362	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(biolink:anatomical_context_qualifier=GO:0005829)&&(biolink:anatomical_context_qualifier=GO:0005654)
REACTO:R-HSA-390765	biolink:affects	REACTO:R-HSA-5660649	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(biolink:anatomical_context_qualifier=GO:0005829)&&(biolink:anatomical_context_qualifier=GO:0005654)
REACTO:R-HSA-390765	biolink:affects	REACTO:R-HSA-5660656	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(biolink:anatomical_context_qualifier=GO:0005829)
REACTO:R-HSA-390765	biolink:affects	UniProtKB:O75582	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(biolink:anatomical_context_qualifier=GO:0005829)&&(biolink:anatomical_context_qualifier=GO:0005654)
REACTO:R-HSA-390765	biolink:affects	UniProtKB:Q01201	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(biolink:anatomical_context_qualifier=GO:0005829)
REACTO:R-HSA-390765	biolink:affects	UniProtKB:P22612	http://model.geneontology.org/R-HSA-5621575	infores:go-cam	(biolink:anatomical_context_qualifier=GO:0005829)&&(biolink:anatomical_context_qualifier=GO:0005654)
```

This PR still uses biolink_quad to create the qualifiers (e.g. `biolink_quad(s, BIOLINK_AFFECTS, o, g), biolink_quad(s, BIOLINK_ACTIVE_IN, l, g), direct_type(l, location).`), but hey, it works! I'll replace this with `quad()` level logic in another PR.

**Pull request merged**
